name: Deploy Databricks Notebooks

on:
  push:
    branches:
      - main
      - main

jobs:

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Configure Databricks CLI (DEV)
        run: |
          databricks configure --token <<EOF
          ${{ secrets.DEV_DEVELOPMENT_TARGET_URL }}
          ${{ secrets.DEV_DEVELOPMENT_TARGET_TOKEN }}
          EOF

      - name: Deploy Notebooks to DEV
        run: |
          databricks workspace import_dir ./notebooks /Shared/dev_notebooks --overwrite


  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Configure Databricks CLI (PROD)
        run: |
          databricks configure --token <<EOF
          ${{ secrets.PROD_DEVELOPMENT_TARGET_URL }}
          ${{ secrets.PROD_DEVELOPMENT_TARGET_TOKEN }}
          EOF

      - name: Deploy Notebooks to PROD
        run: |
          databricks workspace import_dir ./notebooks /Shared/prod_notebooks --overwrite
