name: main

on:
  push: 
    paths-ignore:
      - .github/**
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    strategy:
      matrix:
        include:
          - environment: development
            host_secret: DEV_DEVELOPMENT_TARGET_URL
            token_secret: DEV_DEVELOPMENT_TARGET_TOKEN
            repo_path: /Workspace/Users/tamraj.dhvaj@zohomail.in/DEV-CICD-DATABRICKS-PROJECT
          - environment: production
            host_secret: PROD_DEVELOPMENT_TARGET_URL
            token_secret: PROD_DEVELOPMENT_TARGET_TOKEN
            repo_path: /Workspace/Users/tamraj.dhvaj@zohomail.in/PROD-CICD-DATABRICKS-PROJECT

    env:
      DATABRICKS_HOST: ${{ secrets[matrix.host_secret] }}
      DATABRICKS_TOKEN: ${{ secrets[matrix.token_secret] }}
      REPO_PATH: ${{ matrix.repo_path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@v0.212.2

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Update Databricks Repo
        run: databricks repos update "${{ env.REPO_PATH }}" --branch "${{ steps.extract_branch.outputs.branch }}"
